from __future__ import annotations

from typing import Protocol

from ..domain.entities import Task


class TaskRepository(Protocol):
    def next_id(self) -> int: ...
    def list_all(self) -> list[Task]: ...
    def add(self, task: Task) -> None: ...
    def get(self, task_id: int) -> Task | None: ...
    def update(self, task: Task) -> None: ...
    def delete(self, task_id: int) -> None: ...
